import Spring from "../img/Vector3.png";
import Star from "../img/Star 4.png";

const signupBG = [
  {
    id: 0,
    ballStyle: {
      width: "200px",
      height: "200px",
      backgroundImage: "url('../img/Ball1.svg')",
      background: " linear-gradient(92.7deg, #5404FF 7.9%, #BA2AD1 88.1%)",
      boxShadow: "inset 2px 4px 100px #001D6E ",
      position: "absolute",
      top: "120px",
      left: "83px",
      borderRadius: "100%",
    },
  },

  {
    id: 1,
    ballStyle: {
      width: "102px",
      height: "102px",
      backgroundImage: "url('../img/Ball1.svg')",
      background: " linear-gradient(92.7deg, #5404FF 7.9%, #BA2AD1 88.1%)",
      boxShadow: "inset 1.02px 2.04px 51px #001D6E ",
      position: "absolute",
      top: "126px",
      right: "126px",
      borderRadius: "100%",
    },
  },
  {
    id: 2,
    ballStyle: {
      width: "400px",
      height: "200px",
      display: "block",
      background: " linear-gradient(92.7deg, #5404FF 7.9%, #BA2AD1 88.1%)",
      boxShadow: "inset 4px 8px 200px #001D6E ",
      position: "absolute",
      top: "382px",
      right: "-100px",
      borderRadius: " 200px 200px 0 0",
      transform: "rotate(-90deg)",
    },
  },
  {
    id: 3,
    ballStyle: {
      width: "102px",
      height: "102px",
      backgroundImage: "url('../img/Ball1.svg')",
      background: " linear-gradient(92.7deg, #5404FF 7.9%, #BA2AD1 88.1%)",
      boxShadow: "inset 1.02px 2.04px 51px #001D6E",
      position: "absolute",
      top: "1000px",
      bottom: "300px",
      right: "1025px",
      borderRadius: "100%",
    },
  },
  {
    id: 4,
    ballStyle: {
      width: "157.4px",
      height: "126.94px",
      backgroundImage: `url(${Spring})`,
      background: " linear-gradient(92.7deg, #5404FF 7.9%, #BA2AD1 88.1%)",
      backgroundRepeat: "no-repeat",
      position: "absolute",
      top: "450px",
      right: "220px",
      transform: "rotate(10deg)",
    },
  },
  {
    id: 5,
    ballStyle: {
      width: "157.4px",
      height: "126.94px",
      backgroundImage: `url(${Star})`,
      background: " linear-gradient(92.7deg, #5404FF 7.9%, #BA2AD1 88.1%)",
      backgroundRepeat: "no-repeat",
      position: "absolute",
      top: "700px",
      right: "220px",
      transform: "rotate(10deg)",
    },
  },
  // {
  //   id: 6,
  //   ballStyle: {
  //     width: "157.4px",
  //     height: "126.94px",
  //     backgroundImage: `url(${Star})`,
  //     background: " linear-gradient(92.7deg, #5404FF 7.9%, #BA2AD1 88.1%)",
  //     backgroundRepeat: "no-repeat",
  //     position: "absolute",
  //     top: "450px",
  //     right: "220px",
  //     transform: "rotate(10deg)",
  //   },
  // },
  // {
  //   id: 7,
  //   ballStyle: {
  //     width: "157.4px",
  //     height: "126.94px",
  //     backgroundImage: `url(${Star})`,
  //     background: " linear-gradient(92.7deg, #5404FF 7.9%, #BA2AD1 88.1%)",
  //     backgroundRepeat: "no-repeat",
  //     position: "absolute",
  //     top: "450px",
  //     right: "220px",
  //     transform: "rotate(10deg)",
  //   },
  // },
  // {
  //   id: 8,
  //   ballStyle: {
  //     width: "157.4px",
  //     height: "126.94px",
  //     backgroundImage: `url(${Star})`,
  //     background: " linear-gradient(92.7deg, #5404FF 7.9%, #BA2AD1 88.1%)",
  //     backgroundRepeat: "no-repeat",
  //     position: "absolute",
  //     top: "450px",
  //     right: "220px",
  //     transform: "rotate(10deg)",
  //   },
  // },
  // {
  //   id: 9,
  //   ballStyle: {
  //     width: "157.4px",
  //     height: "126.94px",
  //     backgroundImage: `url(${Star})`,
  //     background: " linear-gradient(92.7deg, #5404FF 7.9%, #BA2AD1 88.1%)",
  //     backgroundRepeat: "no-repeat",
  //     position: "absolute",
  //     top: "450px",
  //     right: "220px",
  //     transform: "rotate(10deg)",
  //   },
  // },
  // {
  //   id: 10,
  //   ballStyle: {
  //     width: "157.4px",
  //     height: "126.94px",
  //     backgroundImage: `url(${Star})`,
  //     background: " linear-gradient(92.7deg, #5404FF 7.9%, #BA2AD1 88.1%)",
  //     backgroundRepeat: "no-repeat",
  //     position: "absolute",
  //     top: "450px",
  //     right: "220px",
  //     transform: "rotate(10deg)",
  //   },
  // },
  // {
  //   id: 11,
  //   ballStyle: {
  //     width: "157.4px",
  //     height: "126.94px",
  //     backgroundImage: `url(${Star})`,
  //     background: " linear-gradient(92.7deg, #5404FF 7.9%, #BA2AD1 88.1%)",
  //     backgroundRepeat: "no-repeat",
  //     position: "absolute",
  //     top: "450px",
  //     right: "220px",
  //     transform: "rotate(10deg)",
  //   },
  // },
];

export default signupBG;
